volumes:
  postgres_data_dev:
  postgres_data_prod:
  postgres_data_test:
  bundle_cache_dev:
  bundle_cache_prod:
  bundle_cache_test:
  redis_data_dev:
  redis_data_prod:

x-env_dev: &env_dev
  REDIS_URL: redis://redis-dev:6379/0
  RAILS_ENV: development
  PG_USERNAME: rockets_u
  PG_PASSWORD: rockets_p
  PG_HOST: postgres-dev
  PG_PORT: 5432
  PG_DATABASE_DEV: rockets_development
  PG_DATABASE_TEST: rockets_test
  PG_DATABASE_PROD: rockets_production
  SECRET_KEY_BASE: dummy_dev_key

x-env_prod: &env_prod
  REDIS_URL: redis://redis-prod:6379/0
  RAILS_ENV: production
  PG_USERNAME: rockets_u
  PG_PASSWORD: rockets_p
  PG_HOST: postgres-prod
  PG_PORT: 5432
  PG_DATABASE_DEV: rockets_development
  PG_DATABASE_TEST: rockets_test
  PG_DATABASE_PROD: rockets_production
  SECRET_KEY_BASE: dummy_production_key

x-env_test: &env_test
  # REDIS_URL: redis://redis-test:6379/0
  RAILS_ENV: test
  PG_USERNAME: rockets_u
  PG_PASSWORD: rockets_p
  PG_HOST: postgres-test
  PG_PORT: 5432
  PG_DATABASE_DEV: rockets_development
  PG_DATABASE_TEST: rockets_test
  PG_DATABASE_PROD: rockets_production
  SECRET_KEY_BASE: dummy_production_key

services:
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/rails
      - bundle_cache_dev:/usr/local/bundle
    ports:
      - "5024:3000"
    depends_on:
      postgres-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
    environment:
      <<: *env_dev
    stdin_open: true
    tty: true

  api-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -e production -b 0.0.0.0"
    volumes:
      - bundle_cache_test:/usr/local/bundle
    ports:
      - "7024:3000"
    depends_on:
      postgres-test:
        condition: service_healthy
      # redis-prod:
      #   condition: service_healthy
    environment:
      <<: *env_test
    stdin_open: true
    tty: true

  api-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -e production -b 0.0.0.0"
    volumes:
      - bundle_cache_prod:/usr/local/bundle
    ports:
      - "6024:3000"
    depends_on:
      postgres-prod:
        condition: service_healthy
      redis-prod:
        condition: service_healthy
    environment:
      <<: *env_prod
    stdin_open: true
    tty: true

  jobs-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -lc "bundle exec sidekiq -c 5 -q default -q mailers"
    volumes:
      - .:/rails
      - bundle_cache_dev:/usr/local/bundle
    depends_on:
      postgres-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
    environment:
      <<: *env_dev
    restart: unless-stopped
    stdin_open: true
    tty: true

  jobs-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -lc "bundle exec sidekiq -e production -c 10 -q default -q mailers"
    volumes:
      - bundle_cache_prod:/usr/local/bundle
    depends_on:
      postgres-prod:
        condition: service_healthy
      redis-prod:
        condition: service_healthy
    environment:
      <<: *env_prod
    restart: unless-stopped

  postgres-dev:
    image: postgres:16
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rockets_u
      POSTGRES_PASSWORD: rockets_p
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "rockets_u", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:16
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rockets_u
      POSTGRES_PASSWORD: rockets_p
      POSTGRES_DB: postgres
    ports:
      - "6432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "rockets_u", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-prod:
    image: postgres:16
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rockets_u
      POSTGRES_PASSWORD: rockets_p
      POSTGRES_DB: postgres
    ports:
      - "6432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "rockets_u", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-dev:
    image: redis:7-alpine
    volumes:
      - redis_data_dev:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-prod:
    image: redis:7-alpine
    volumes:
      - redis_data_prod:/data
    ports:
      - "6479:6379"
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

