default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 50 } %>

development:
  <<: *default
  username: <%= ENV.fetch("PG_USERNAME") %>
  password: <%= ENV.fetch("PG_PASSWORD") %>
  database: <%= ENV.fetch("PG_DATABASE_DEV") %>
  host: <%= ENV.fetch("PG_HOST") %>
  port: <%= ENV.fetch("PG_PORT") %>

test:
  <<: *default
  username: <%= ENV.fetch("PG_USERNAME") %>
  password: <%= ENV.fetch("PG_PASSWORD") %>
  database: <%= ENV.fetch("PG_DATABASE_TEST") %>
  host: <%= ENV.fetch("PG_HOST") %>
  port: <%= ENV.fetch("PG_PORT") %>

production:
  <<: *default
  username: <%= ENV.fetch("PG_USERNAME") %>
  password: <%= ENV.fetch("PG_PASSWORD") %>
  database: <%= ENV.fetch("PG_DATABASE_PROD") %>
  host: <%= ENV.fetch("PG_HOST") %>
  port: <%= ENV.fetch("PG_PORT") %>
